### ISSUE TITLE
Compiling on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by cultpenguin** [GAIA-UNIL/G2S#33]
When I compile the Matlab interface I using 'CompileG2S' I get an error that "json/json.h" cannot be found, in the line  
#include <json/json.h> 

If I add the following soft link the compilation works fine

sudo ln -s /usr/include/jsoncpp/json/ /usr/include/json

I use Ubuntu 18.04.3 LTS

- Thomas

**Comment by mgravey** [comment]
I added a new branch https://github.com/GAIA-UNIL/G2S/tree/fix-G2S-matlab-compilation, it should solve the issue, if it work I will merge it

Thanks,
Mathieu

**Comment by mgravey** [comment]
The branch was merged !
