### ISSUE TITLE
Problem with the build process

### ISSUE THREAD

**Issue by joaoponte** [GAIA-UNIL/G2S#53]
**Describe the bug**
Problem with the installation process.
I tried the simple way (pip), but they also didn't work.
The script with gcc apparently goes pretty well,  but when installing with pip, I get the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joao/miniconda3/envs/dl/lib/python3.8/site-packages/g2s/__init__.py", line 12, in <module>
    from .g2s import run
ImportError: /home/joao/miniconda3/envs/dl/lib/python3.8/site-packages/g2s/g2s.cpython-38-x86_64-linux-gnu.so: undefined symbol: gzrewind
```

I found that a possible solution was to build the interface/server with the -lz argument in the last position, so I did.
The server build appeared to be successful, but the python interface give the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module><br>
  File "/home/joao/bibliotecas/G2S/build/python-build/g2s/__init__.py", line 12, in <module><br>
    from .g2s import run<br>
ModuleNotFoundError: No module named 'g2s.g2s'  
```

**Information**
- interface : Python 3.8.10
- OS: Ubuntu 20.04
- 0.97.007 with manual installation and 0.97.7 with pip

**To Reproduce**
I created a new conda env, cloned the git repository and followed the step-by-step guide (https://gaia-unil.github.io/G2S/) to manual build the server and the python interface.

**Test**
If possible a small code that reproduce the bug

**Expected behavior**
Both server's build and interface's build returns no errors and the follow code returns the right version.
`from g2s import g2s; g2s('--version')`

**Additional context**
As a somewhat beginner with make and setup.py, I couldn't find a solution to this problem.
Did I do something wrong with the installation process?
The process is apparently very straight-forward and easy, so I probably messed something up…

**Comment by mgravey** [comment]
Hi Joao,

I think you try to run the import of g2s in the "G2S/build/python-build/" directory. It's the only place in the computer that where it will not work :) (example: https://colab.research.google.com/drive/1az9j-xGXiUHZgXL2d_x3xe8DFCdYqMj1?usp=sharing )
Simply move to another folder then it should work.

Let me know if it is another problem 

Mathieu

**Comment by joaoponte** [comment]
Hi Mathieu,

Thanks for your answer!
This indeed solved the `ModuleNotFoundError` problem, thank you very much!
However, I followed the same steps present in the example and the `undefined symbol: gzrewind` error still persists.
I checked the versions of zlib of the Google Colab and they matched with the versions in my computer.

I honestly can't tell why the error persisted, :/
Have you any idea?
Maybe it is a problem with the includes/libs on my system or something similar...

**Comment by mgravey** [comment]
and out side of conda ?
Try to copy the zlib directly in the g2s folder

**Comment by joaoponte** [comment]
In the native python worked perfectly!

I copied the zlib to the g2s folder in this conda env, rebuilt the repo and I got the same error as before.
The version of my zlib is the 1.2.11.
I tested also in my personal computer (WSL2 with Ubuntu 20.04), which also has conda, and it returned the same error.

It is probably a weird problem related to conda in some way...

Thank you for the help so far!

**Comment by joaoponte** [comment]
Just a small update, I found out what was the problem!
I don't know exactly the reason why, but I needed to add the zlib to the compiler.

So I changed the line 30 of the setup.py file from:
`extraLib=['jsoncpp'];`

to

`extraLib=['jsoncpp', 'z'];`

Just to add the zlib reference to the compiler and the code `from g2s import g2s; g2s('--version')` returned the expected output.
