### ISSUE TITLE
Issue importing G2S for Python

### ISSUE THREAD

**Issue by maxwnewcomer** [GAIA-UNIL/G2S#54]
When trying to import g2s into python after installing g2s through pip I get,

```
from g2s import g2s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/lib/python3.8/site-packages/g2s/__init__.py", line 12, in <module>
    from .g2s import run
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/anaconda3/lib/python3.8/site-packages/g2s/g2s.cpython-38-x86_64-linux-gnu.so)
```

After trying to replace the libstdc++.so.6 version with an updated version that contains GLIBCXX_3.4.26, I am still receiving the error.

**Comment by maxwnewcomer** [comment]
After some troubleshooting with @mgravey, discovered simply `conda install libgcc=7.2.0` fixed this issue.

**Comment by mgravey** [comment]
I improve the compilation to reduce dependencies, and it looks like now it will work even without `libgcc=7.2.0`
