### ISSUE TITLE
failed to do simulation or return simulation results 

### ISSUE THREAD

**Issue by A-DCA** [GAIA-UNIL/G2S#57]
Hello there,

I downloaded and compiled c++ and python. They both seemed to work. I can launch server and get return from g2s import g2s; g2s('--version') as "G2S version 0.98.002, compiled the Mar 20 2022 15:34:39 with Python 3.8.12".

However, when I run example codes, i.e. unconditionalSimulation.py, data=g2s('-a','qs', '-ti',ti, ...) returns job Id is: 1911726720 and (-0.001, -1.0, 1911726720) as I print(data)
I have checked ti beng downloaded was correctly plotted out on screen after commented out #ax2.imshow(simulation).  

I noticed there were one or two bgrid.zip files in ./data but nothing in logs. When stderr of the server was redirected to a file, it contains the following message "can not open file : logs/1911726720.log".  

Could you please advise a solution? I did not see an automatic test was carried before compiling client code, but noticed other executables     

I compiled g2s on wsl ubuntu 20.04 with gcc/g++ 9.3.0 and all standard settings in makefile but turn-off gpu support for now but noticed codes listed in algosName.config. Could they be used for checking server status?      

Thanks,

Jingsheng Ma

**Comment by mgravey** [comment]
Hi Jingsheng,
strange usually I don't have any issue with WSL support
do you know if you use WSL 2 of WSL 1 ?
Did you install WSL for G2S or had you already it before ?
Your python is a window python or you use pythons in WSL ? (both should work)

Can you try ?
`result=g2s('-a','echo','-ti',ti,'-dt',[0])`
this should return the ti

Did you take the example from the website or from the example folder (try from the other source).

BTW, I never try CUDA on WSL, but based on the NVIDIA webpage it should just work fine. 

Best,
Mathieu

**Comment by A-DCA** [comment]
Hi Mathieu,

Thanks for your quick reply.

I am using: wsl2, and had it installed before installing g2s.

I compiled g2s and its python interface all under wsl2 and run the server and python scripts under wsl2 too.

I have now found your test.py in python-build dir and modified it by adding lines to get the stone image online (copied from unconditionalSimulation.py from the example dir in the cloned package) and the echo line you suggested.

I enclose the script I executed  and stderr and stdout from client and server for your information.  I added print out infoRequest.task to server.cpp so that you see “request=”. I also enclose the data dir which contains a bgrid file. I assume that contain the stone image.

I have also run test.py with added lines commented out, the same problem occurred.  I had two png files saved at ../TrainingImages locally.

Kind regards,

Jingsheng

PS. I will turn on GPU later. CUDA and CUDNN worked fine on WSL2 on my machine.

**Comment by mgravey** [comment]
Were you able to make it work ?

**Comment by A-DCA** [comment]
No. I tried ./echo and ./qs but both caused segmentation faults. Then I recompiled with the default makefile, but they caused the same error.

Did you compile/run g2s successfully on ubuntu 20.04 on WSL2 or 18.04?

I thought to try it on another machine but our VPN down for past a few days.

**Comment by mgravey** [comment]
Yep! More precisely Ubuntu 20.04.4 with WSL2 on windows 11.

I have the filling that maybe a library didn’t link correctly, what is the output of  `ldd ./qs`

**Comment by A-DCA** [comment]
Here is it.

**Comment by mgravey** [comment]
Nope, it looks good.

If you want we can do a call (contact me in private) to debug this, I can not imagine that it's a big issue.

**Comment by A-DCA** [comment]
Thanks for your offer and helps.

I think I will try to compile it on a remote machine first. That will be more ideal for doing intensive simulations anyway.

If I still have problem, I will contact you to do a debug.

Kind regards,

Jingsheng
