### ISSUE TITLE
libzmq.so.5 not found

### ISSUE THREAD

**Issue by martin-wegmann** [GAIA-UNIL/G2S#66]
Hello G2S Team,

I tried to install G2S for python on the Bernese supercomputer in my conda environment.

Installing with pip install G2S went fine, but calling it with import G2S is unfortunately giving me:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/storage/homefs/mawegmann/.conda/envs/tfgpu/lib/python3.7/site-packages/g2s/__init__.py", line 12, in <module>
    from .g2s import run
ImportError: libzmq.so.5: cannot open shared object file: No such file or directory

It is a UNIX environment where I don't have sudo rights. Any idea on how to approach this issue is appreciated.

All the best,
Martin

**Comment by mgravey** [comment]
I have moved the ZMQ dependancy as static, can you update with `pip install  G2S -i https://test.pypi.org/simple/ --upgrade` and tell if it work?, if it work I will move it to the main PIP repository

**Comment by mgravey** [comment]
no news, I assume it's solved
